### ISSUE TITLE
Crash on spawn?

### ISSUE THREAD

**Issue by devryb** [TheRoBrit/Moo-Fluids#16]
Not really sure when this crash occurs if its a fluid cow spawning or what but thought I'd report it at least.

http://pastebin.com/B05ppBG8

**Comment by TheRoBrit** [comment]
I will have to look into this issue.

If you can provide me with any additional information that could help me to replicate this issue that'd be much appreciated. If not, thank you for the logs.

**Comment by skulldrago** [comment]
i have the same error. it came all 2 hours. i think it have to do with the save of spawndata. Could it be that your mod is saving all cows at one time and that could cause a outofmemory at servers?

**Comment by TheRoBrit** [comment]
I really do not believe that is the case. Please provide me with a crash report as without it I cannot determine it is the same issue as stated in this thread. 

Also, the NBT data (that is saved and loaded) is done PER cow (at varying points) so I highly doubt that'd be causing out of memory errors any more so than any other vanilla/modded entity.

**Comment by skulldrago** [comment]
Hey here my crash log of the server:
http://pastebin.com/TBGcv1Gn
after i removed your mod the error was gone. I will add it if i can fix that crash issue because it is a cool mod

**Comment by PureSpider** [comment]
I get the same bug, it crashes my server a lot and the cow in question is gone after a server restart (obviously, since it didn't save correctly).
http://pastebin.com/NQiqD612
