### ISSUE TITLE
Timer resets when clicked with hand

### ISSUE THREAD

**Issue by TheFjonG** [TheRoBrit/Moo-Fluids#18]
Can you change line 91 in https://github.com/TheRoBrit/Moo-Fluids/blob/master/src/main/java/com/robrit/moofluids/common/entity/EntityFluidCow.java to something that checks whether the held item is a fluid container or not? ;)... Please :)

**Comment by TheFjonG** [comment]
Line 91: if (getCurrentUseCooldown() == 0) {} to if (getCurrentUseCooldown() == 0 && FluidContainerRegistry.isEmptyContainer(currentItemStack)) {} ? :+1:

**Comment by TheRoBrit** [comment]
Good spot, your solution is an improvement to the logic but would still allow for fluid containers that could not viably be used (for that particular cow) to reset the timer. But I have found an appropriate way of fixing this. 

Thanks for the report.
