### ISSUE TITLE
MooFluid Cow acting as blizz

### ISSUE THREAD

**Issue by coolacid** [TheRoBrit/Moo-Fluids#19]
Running Skyfactory 2 - MooFluids-1.7.10-1.5.01.19a.jar - ThermalFoundation-[1.7.10]1.0.0RC7-62.jar

Spawned in a Taiga Biome.  Normal blizz's will spawn. However, in my mob farm, there appeared to be moo-fluid cows also spawning. Captured 2 in safari nets and both indicated Blizz as the description. Captured in a re-useable net, and placed in an MFR Auto-Spawner yielded a number of moo-fluid cows that starting tossing snowballs at me and flying around. 

For reference - cofh's registration line :: https://github.com/CoFH/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/entity/monster/EntityBlizz.java#L88

I have no idea how the entities are getting crossed. 

Other notes as I try and see what's going on. 
- I tried to milk a cow and got mixed results. At one point, I had a bucket of fluid, but when trying to access my AE2 system, the liquid disappeared. 
- When I went back to try and milk the cow again, the cow disappeared as well.

**Comment by TheRoBrit** [comment]
I really have no idea on this one, if you can provide steps on how to replicate this issue please let me know... this is neither intended behaviour nor something I even understand as to how it's happening if I'm quite honest.

Failing steps to replicate this issues I doubt I will be able to fix it as it will be a real shot in the dark.

Thanks for the report regardless though.

**Comment by coolacid** [comment]
Yep, when I read the two codes I couldn't see any reason why either. I don't know the internals of Modded minecraft and the only thing I could think of was a race condition between the two mods getting the same ID. 

Currently trying to recreate it in a new world. 

Seed: -7895155262725874054
Basic mob spawner 

The only difference this time is that it's local instead of a separate server.  

Currently waiting for blizz to spawn. 

Edit: 

To complicate it even further - I checked the spawn eggs for the two entities:
383:7 for the cow, 383:23 for the Blizz.

**Comment by TheRoBrit** [comment]
Hmmm, I don't believe that this is on my part. But I shall look into this as I am actually intrigued as to why this issue occurs. I will attempt to replicate and possibly address this issue as and when I am available to do so. Thanks for furthering the details on your issue. Much appreciated.
