### ISSUE TITLE
Crash while walking across the world

### ISSUE THREAD

**Issue by Mortishorse** [TheRoBrit/Moo-Fluids#22]
http://pastebin.com/A8ctdEtm 

Null pointer exception while saving MooFluidCow NBT data.
 com.robrit.moofluids.common.entity.EntityFluidCow.func_70014_b(Entity
FluidCow.java:313) 

MooFluids-1.7.10-1.5.01.19a.jar under custom ResonantRise3261RC

**Comment by PureSpider** [comment]
I get the same bug a lot, crashes the server and the cow that didn't save properly is gone after a restart.

**Comment by PureSpider** [comment]
Also see #16 and #20 for the same bug.
