### ISSUE TITLE
Startup Crash with Forever Enough Items--1.8.9

### ISSUE THREAD

**Issue by Bersham** [TheRoBrit/Moo-Fluids#35]
#https://github.com/elix-x/Forever-Enough-Items/issues/16

Moo Fluids and FEI cause a crash during startup. Removing one or the other allows the game to startup just fine.

ExCore 1.0
FEI 1.0
JEI 2.28.18.186
Moo Fluids 1.6.03.20a
Forge 11.15.1.1902

[Latest Log](https://pastenib.com/v/6PxyDgUZHLwIrHZw7rGq)
[Crash Report](https://pastenib.com/v/chTOLXud0PrLJs3EcNjN)

**Comment by TheRoBrit** [comment]
Issue closed due to cross-mod interaction issue being related to 3rd party (other mod involved in cross-mod interaction).
