### ISSUE TITLE
Cant store fluids in buckets

### ISSUE THREAD

**Issue by TruckerTorpedo** [TheRoBrit/Moo-Fluids#36]
When i rightclick a cow with a bucket, it resets the tick counter, fills the bucket, but if i place the fluid into the world, it just vanishes. same thing if i open my inventory. what could be the cause of this?
Edit: i milked with the mfr rancher, and was able to pick up the fluid from it with a portable tank, then i could but it in a bucket. but rightclicking a cow with a bucket or tank, just resets the counter, and erases the fluid.

**Comment by JSchober93** [comment]
This issue is still happening
