### ISSUE TITLE
[Feature] WAILA Integration?

### ISSUE THREAD

**Issue by greenrhino33** [TheRoBrit/Moo-Fluids#4]
Any way you could get WAILA to show which fluid the cow is? Also, the WAILA readout of any cow is "entity.EntityFluidCow.name", probably a localization bug.

**Comment by TheRoBrit** [comment]
I am actively working on adding WAILA support that will contain the Cow's fluid and the current cooldown time. Hope to see it added soon.

**Comment by greenrhino33** [comment]
Ah, good. Thanks a bunch!

**Comment by TheRoBrit** [comment]
WAILA support done. Will be in the next build. Issue closed.

**Comment by Goobaroo** [comment]
I believe this is currently broken.  Or there is a requirement in order to enable it.

**Comment by ThexXTURBOXx** [comment]
@Goobaroo See my answer in #45 ;) Hope it works for you, too ^^
