### ISSUE TITLE
The One Prob Support

### ISSUE THREAD

**Issue by twizcraft** [TheRoBrit/Moo-Fluids#47]
Can we get support for The one Probe so it will show what type of fluid the cows are in 1.10.2 please and thanks

**Comment by Jo-Mamma75** [comment]
And as an alternative or addition to would it be possible to add support to Hwyla (the successor of Waila) to show the type of cow and cool-down period for the 1.10.2 version of the mod?

**Comment by TheRoBrit** [comment]
Duplicate of #45. Closing.
