### ISSUE TITLE
Thaummcraft Aspect registry cause crash

### ISSUE THREAD

**Issue by apheliotropism** [TheRoBrit/Moo-Fluids#5]
Using MooFluids1.5.01.03b and ThaumCraft4.2.2.1, game crash on startup.
Crash report: http://pastebin.com/44eW93C5

**Comment by TheRoBrit** [comment]
Added a check for whether fluid actually has a block. Will be in next build. Issue closed.

**Comment by apheliotropism** [comment]
Thanks for helping. > <
