### ISSUE TITLE
I CANT MILK THE COWS FFS

### ISSUE THREAD

**Issue by DaniPetrov** [TheRoBrit/Moo-Fluids#50]
i cant milk them in the Foolcraft modpack. I looked in the config and didn't find anything. Btw the modpack is in 1.10.2

**Comment by Lycanic** [comment]
After spawning they're still on cooldown. Have you left them a while (10 min) before trying to milk?

**Comment by MeinKraft** [comment]
i found by editing the config file and reducing their cooldown to 200, should work - thats about every 5 seconds they can be milked
