### ISSUE TITLE
Texture Tint not showing [1.12.2]

### ISSUE THREAD

**Issue by PssbleTrngle** [TheRoBrit/Moo-Fluids#70]
The Fluid cows are rendering like normal ones (without the color tint).
I'm trying to figure out what mod is causing it, but I had no success so far.
It's neither Optifine, nor Quark.
The mod version I am using is 1.7.11.02a.
 I attached a file containing the names of all loaded mods:

[modlist.txt](https://github.com/TheRoBrit/Moo-Fluids/files/1866281/modlist.txt)

**Comment by FireFlyerFighter** [comment]
I figured out that it is caused by Albedo
