### ISSUE TITLE
MooFluids Half Gone, Also Causing Crashes

### ISSUE THREAD

**Issue by knoxhack** [TheRoBrit/Moo-Fluids#82]
Bug Report
Steps to Reproduce (for bugs)
Have moo fluid cows, try spawning the cows to get ones I had from before I updated.
Server Crashes when MooFluids come into play
Logs
Client/Server Log:
https://github.com/Sunekaer/stoneBlock/files/2472234/debug.log
https://github.com/Sunekaer/stoneBlock/files/2472231/latest.log
Crash Log:
https://github.com/Sunekaer/stoneBlock/files/2472235/crash-2018-10-12_02.27.33-server.txt
https://github.com/Sunekaer/stoneBlock/files/2472236/crash-2018-10-12_03.18.53-server.txt

Client Information
Modpack: StoneBlock 1.0.20
Minecraft: 1.12.2
Forge: forge-14.23.5.2768

**Comment by Benedictum** [comment]
I have similar behavior in stoneblock. Missing about 40 types of fluid cows, the following were in animal nets and when i used them to put the cow back in the world they just emptied. I made a mob duplicator with a fluid cow in it and spat out 514 cows, none of the following types spawned.

dark steel
conductive iron
energetic alloy
gold
end steel
iron
soularium
steel
osmium
nickel
bronze
pulsating iron
copper
manasteel
elementium
terrasteel
osmiridium
redstone alloy
lead
brass
electrum
refined uranium
ardite
evil infused
manyullun
refined obsidian
pigiron
knightslime
demon metal
vibrant alloy

Many other fluids also did not spawn but those are the ones i am tracking. of the 514 i spawned, majority were of the following types:
constantin, invar, electrical steel, sap, resin, grassoline, essence of knowledge, primal mana, destabilized redstone, enderium, resonant ender, lava, crystalized oil, water, heavy water, energized glowstone, seed oil, platinum, tectonic petrotheum, mushroom stew, signalum, blazing pyrotheum, gelid cryotheum, potions, resin, tree oil, etc.
